### ISSUE TITLE
bank captcha

### ISSUE THREAD

**Issue by sinoa002** [3Shain/yet-another-anime-game-launcher#257]
**Describe the bug**
When I was trying to log in, it popped up with this blank captcha

**Screenshots**
<img width="1280" alt="截圖 2024-02-05 下午4 33 48" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/159005466/38c092d3-ad27-4934-880a-078dbc97ad5d">

**System Information (please complete the following information):**
 - macOS: [e.g. 14.4 beta Ventura]
 - Device: [e.g. MacbookAir M2 ]
 - CPU: [e.g. Apple M2 ]
 - RAM: [e.g. 8G ]

**Comment by panthark** [comment]
i have this too

**Comment by thisaint1230** [comment]
I just fixed that bug when I update my OS to sonoma 14.4.2 beta. plz try it

**Comment by panthark** [comment]
i just did that and i tryed again, and its still not working. Im deleting everything and redownloading

**Comment by panthark** [comment]
still nothing, blank captcha after getting no verification code, stuck on a black screen if it I try logging in through twitter or facebook, honestly super frustrating havent been able to play since like mid december bc or random issues

**Comment by panthark** [comment]
yes still doesnt work

**Comment by ahmadInternaldo** [comment]
> **Describe the bug** When I was trying to log in, it popped up with this blank captcha
> 
> **Screenshots** <img alt="截圖 2024-02-05 下午4 33 48" width="1280" src="https://private-user-images.githubusercontent.com/159005466/302226406-38c092d3-ad27-4934-880a-078dbc97ad5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTAyNjUsIm5iZiI6MTcwODA4OTk2NSwicGF0aCI6Ii8xNTkwMDU0NjYvMzAyMjI2NDA2LTM4YzA5MmQzLWFkMjctNDkzNC04ODBhLTA3OGRiYzk3YWQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxMzI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDBkNDYyNWVmNzUyNDUyZWE0M2NkZDg2NWNjOGExYzhjMjYxOTM1Y2JhY2VmOTc0MjcxZmVmMDE0YzM4N2MzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zYVEKvuVF2Mf8XTHGNfnMFQuIVmeWdVTQxxokkWaOZo">
> 
> **System Information (please complete the following information):**
> 
> * macOS: [e.g. 14.4 beta Ventura]
> * Device: [e.g. MacbookAir M2 ]
> * CPU: [e.g. Apple M2 ]
> * RAM: [e.g. 8G ]

it work in my mac
1. run step -> uncheck the turn off the patch, then login again
2. the capta will appear in my mac, but after success will get error, its okay cause your already login
3. exit (but not logout), then re setting (check the turn off the patch)
4. relaunch the game

hope will help yours

**Comment by 3Shain** [comment]
ahmadInternaldo just gives the solution (close as duplicate of https://github.com/3Shain/yet-another-anime-game-launcher/issues/255#issuecomment-1950778029
